from typing import Protocol

from core.dns_record import Record


class DnsRegistry(Protocol):
    def register(self, record: Record): ...
    def remove(self, record: Record): ...
    def list(self) -> list[Record]: ...
